FROM node:24-alpine

# This provides the 'openssl' and 'libc6-compat' Prisma needs
RUN apk add --no-cache openssl libc6-compat

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

RUN npx prisma generate

COPY . .

EXPOSE 5000

CMD ["npm", "run", "dev"]